name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_NAME: evertech/ca3
        DOCKER_IMAGE_TAG: latest
        DOCKER_USERNAME: evertech
      run: |
        docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
        echo 14octqwerty | docker login -u evrtech --password-stdin
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
